export const SOURCE_CATEGORIES = {
  LOCAL_MEMORY: 'local_memory',
  EVIDENCE_CACHE: 'evidence_cache',
  SEARCH_METADATA: 'search_metadata',
  OFFICIAL_API: 'official_api',
  WEBSITE_ENRICHMENT: 'website_enrichment',
  EMAIL_ENRICHMENT: 'email_enrichment',
  OFFLINE_CORPUS: 'offline_corpus',
  DATASET_IMPORT: 'dataset_import',
  ADMIN_ONLY_OSINT: 'admin_only_osint',
  RESEARCH_CATALOG: 'research_catalog',
  BLOCKED_RUNTIME: 'blocked_runtime',
};

export const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  BLOCKED: 'BLOCKED',
};

export const COST_LEVELS = {
  FREE: 'FREE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  UNKNOWN: 'UNKNOWN',
};

export const STAGES = {
  LOCAL_SEARCH: 'LOCAL_SEARCH',
  EVIDENCE_REUSE: 'EVIDENCE_REUSE',
  LIVE_DISCOVERY: 'LIVE_DISCOVERY',
  OFFICIAL_LOCAL_BUSINESS: 'OFFICIAL_LOCAL_BUSINESS',
  WEBSITE_ENRICHMENT: 'WEBSITE_ENRICHMENT',
  EMAIL_ENRICHMENT: 'EMAIL_ENRICHMENT',
  OFFLINE_MINING: 'OFFLINE_MINING',
  ADMIN_IMPORT: 'ADMIN_IMPORT',
  ADMIN_RESEARCH: 'ADMIN_RESEARCH',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
};

const POLICIES = {
  LOCAL_DATASET: {
    key: 'LOCAL_DATASET',
    label: 'Local Dataset',
    category: SOURCE_CATEGORIES.LOCAL_MEMORY,
    runtimeAllowed: true,
    userCampaignAllowed: true,
    adminImportAllowed: true,
    adminOnly: false,
    enrichmentAllowed: false,
    offlineOnly: false,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: false,
    canRunForUserCampaign: true,
    canRunAutomatically: true,
    allowedStages: [STAGES.LOCAL_SEARCH],
    blockedStages: [],
    notes: 'Primary fast data source.',
    disabledReason: null,
  },
  LEAD_EVIDENCE_CACHE: {
    key: 'LEAD_EVIDENCE_CACHE',
    label: 'Lead Evidence Cache',
    category: SOURCE_CATEGORIES.EVIDENCE_CACHE,
    runtimeAllowed: true,
    userCampaignAllowed: true,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: false,
    offlineOnly: false,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: false,
    canPromoteToCatalog: true,
    canRunForUserCampaign: true,
    canRunAutomatically: true,
    allowedStages: [STAGES.EVIDENCE_REUSE],
    blockedStages: [],
    notes: 'Used to avoid paying for external APIs when recent data exists.',
    disabledReason: null,
  },
  SERPER: {
    key: 'SERPER',
    label: 'Serper.dev',
    category: SOURCE_CATEGORIES.SEARCH_METADATA,
    runtimeAllowed: true,
    userCampaignAllowed: true,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: false,
    offlineOnly: false,
    requiresApiKey: true,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.MEDIUM,
    costLevel: COST_LEVELS.LOW,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: true,
    canRunAutomatically: true,
    allowedStages: [STAGES.LIVE_DISCOVERY],
    blockedStages: [],
    notes: 'Primary search metadata provider.',
    disabledReason: null,
  },
  SERPAPI: {
    key: 'SERPAPI',
    label: 'SerpAPI',
    category: SOURCE_CATEGORIES.SEARCH_METADATA,
    runtimeAllowed: true,
    userCampaignAllowed: true,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: false,
    offlineOnly: false,
    requiresApiKey: true,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.MEDIUM,
    costLevel: COST_LEVELS.MEDIUM,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: true,
    canRunAutomatically: true,
    allowedStages: [STAGES.LIVE_DISCOVERY],
    blockedStages: [],
    notes: 'Fallback search metadata provider.',
    disabledReason: null,
  },
  GOOGLE_PLACES: {
    key: 'GOOGLE_PLACES',
    label: 'Google Places API',
    category: SOURCE_CATEGORIES.OFFICIAL_API,
    runtimeAllowed: true,
    userCampaignAllowed: true,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: true,
    offlineOnly: false,
    requiresApiKey: true,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.MEDIUM,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: true,
    canRunAutomatically: true,
    allowedStages: [STAGES.OFFICIAL_LOCAL_BUSINESS],
    blockedStages: [],
    notes: 'Used only for GOOGLE_MAPS target source / local business intent.',
    disabledReason: null,
  },
  WEBSITE_METADATA: {
    key: 'WEBSITE_METADATA',
    label: 'Website Metadata Fetcher',
    category: SOURCE_CATEGORIES.WEBSITE_ENRICHMENT,
    runtimeAllowed: true,
    userCampaignAllowed: false,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: true,
    offlineOnly: false,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.LOW,
    canCreateEvidence: true,
    canPromoteToCatalog: false,
    canRunForUserCampaign: false,
    canRunAutomatically: true,
    allowedStages: [STAGES.WEBSITE_ENRICHMENT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Not a standalone discovery source. Used to enrich existing leads.',
    disabledReason: null,
  },
  SNOV_IO: {
    key: 'SNOV_IO',
    label: 'Snov.io',
    category: SOURCE_CATEGORIES.EMAIL_ENRICHMENT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: false,
    adminOnly: false,
    enrichmentAllowed: true,
    offlineOnly: false,
    requiresApiKey: true,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.MEDIUM,
    costLevel: COST_LEVELS.HIGH,
    canCreateEvidence: true,
    canPromoteToCatalog: false,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.EMAIL_ENRICHMENT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'For future high-quality lead enrichment only. Not active in this phase.',
    disabledReason: 'Not implemented in this phase.',
  },
  COMMON_CRAWL: {
    key: 'COMMON_CRAWL',
    label: 'Common Crawl',
    category: SOURCE_CATEGORIES.OFFLINE_CORPUS,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.OFFLINE_MINING, STAGES.ADMIN_IMPORT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Huge offline corpus. Cannot be used for live user searches.',
    disabledReason: 'Offline processing only.',
  },
  HUGGING_FACE_DATASETS: {
    key: 'HUGGING_FACE_DATASETS',
    label: 'Hugging Face Datasets',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: true,
    requiresManualReview: true,
    riskLevel: RISK_LEVELS.MEDIUM,
    costLevel: COST_LEVELS.UNKNOWN,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT, STAGES.ADMIN_RESEARCH],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Requires checking licenses before import.',
    disabledReason: 'Requires manual admin verification of datasets.',
  },
  SPIDERFOOT: {
    key: 'SPIDERFOOT',
    label: 'SpiderFoot',
    category: SOURCE_CATEGORIES.ADMIN_ONLY_OSINT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: false,
    adminOnly: true,
    enrichmentAllowed: true,
    offlineOnly: false,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: true,
    riskLevel: RISK_LEVELS.HIGH,
    costLevel: COST_LEVELS.UNKNOWN,
    canCreateEvidence: true,
    canPromoteToCatalog: false,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_RESEARCH],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Too risky and slow for public SaaS runtime. Admin only.',
    disabledReason: 'Admin OSINT tool only.',
  },
  GOOGLE_MAPS_SCRAPER_OUTPUT: {
    key: 'GOOGLE_MAPS_SCRAPER_OUTPUT',
    label: 'Google Maps Scraper Output',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: true,
    riskLevel: RISK_LEVELS.HIGH,
    costLevel: COST_LEVELS.UNKNOWN,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Live scraping maps is blocked. This represents offline output imports.',
    disabledReason: 'Direct runtime scraping is blocked.',
  },
  CSV_IMPORT: {
    key: 'CSV_IMPORT',
    label: 'CSV Import',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Standard data import path.',
    disabledReason: null,
  },
  XLSX_IMPORT: {
    key: 'XLSX_IMPORT',
    label: 'XLSX Import',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Standard data import path.',
    disabledReason: null,
  },
  JSON_IMPORT: {
    key: 'JSON_IMPORT',
    label: 'JSON Import',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.MEDIUM,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT],
    blockedStages: [STAGES.LIVE_DISCOVERY],
    notes: 'Future import path.',
    disabledReason: 'JSON import not exposed yet.',
  },
  MANUAL_ADMIN_IMPORT: {
    key: 'MANUAL_ADMIN_IMPORT',
    label: 'Manual Admin Entry',
    category: SOURCE_CATEGORIES.DATASET_IMPORT,
    runtimeAllowed: false,
    userCampaignAllowed: false,
    adminImportAllowed: true,
    adminOnly: true,
    enrichmentAllowed: false,
    offlineOnly: true,
    requiresApiKey: false,
    requiresLicenseReview: false,
    requiresManualReview: false,
    riskLevel: RISK_LEVELS.LOW,
    costLevel: COST_LEVELS.FREE,
    canCreateEvidence: true,
    canPromoteToCatalog: true,
    canRunForUserCampaign: false,
    canRunAutomatically: false,
    allowedStages: [STAGES.ADMIN_IMPORT],
    blockedStages: [],
    notes: 'Admin manual lead entry.',
    disabledReason: null,
  },
};

export const getSourcePolicy = (key) => POLICIES[key] || null;

export const listSourcePolicies = () => Object.values(POLICIES);

export const listRuntimeAllowedSources = () => listSourcePolicies().filter((p) => p.runtimeAllowed);

export const listOfflineOnlySources = () => listSourcePolicies().filter((p) => p.offlineOnly);

export const listAdminOnlySources = () => listSourcePolicies().filter((p) => p.adminOnly);

export const listBlockedRuntimeSources = () => listSourcePolicies().filter((p) => !p.allowedStages.includes(STAGES.LIVE_DISCOVERY));

export const listSourcesBlockedForStage = (stage) => listSourcePolicies().filter((p) => !p.allowedStages.includes(stage) || p.blockedStages.includes(stage));

export const assertSourceAllowedForStage = (sourceKey, stage) => {
  const policy = getSourcePolicy(sourceKey);
  if (!policy) {
    return { allowed: false, reason: `Unknown source: ${sourceKey}` };
  }
  if (policy.blockedStages.includes(stage)) {
    return { allowed: false, reason: `${policy.label} is explicitly blocked for stage: ${stage}` };
  }
  if (!policy.allowedStages.includes(stage)) {
    return { allowed: false, reason: `${policy.label} is not approved for stage: ${stage}` };
  }
  return { allowed: true };
};

export const explainSourcePolicy = (sourceKey) => {
  const policy = getSourcePolicy(sourceKey);
  if (!policy) return `Source ${sourceKey} is not recognized by the policy engine.`;
  const access = policy.runtimeAllowed ? 'allowed in runtime' : policy.offlineOnly ? 'offline only' : policy.adminOnly ? 'admin only' : 'blocked';
  return `${policy.label} (${policy.category}): ${access}. Risk: ${policy.riskLevel}, Cost: ${policy.costLevel}. ${policy.notes}`;
};

export const getPolicyWarningsForCampaign = (campaign) => {
  const warnings = [];
  const sources = campaign?.sources || [];
  for (const source of sources) {
    const policy = getSourcePolicy(source);
    if (!policy) {
      warnings.push(`Unknown source requested: ${source}`);
    } else if (!policy.userCampaignAllowed) {
      warnings.push(`${policy.label} is not permitted for live user campaigns.`);
    } else if (policy.riskLevel === RISK_LEVELS.HIGH) {
      warnings.push(`${policy.label} carries high execution risk.`);
    }
  }
  return warnings;
};

export const canSourceCreateEvidence = (sourceKey) => getSourcePolicy(sourceKey)?.canCreateEvidence ?? false;

export const canSourcePromoteToCatalog = (sourceKey) => getSourcePolicy(sourceKey)?.canPromoteToCatalog ?? false;
