import { AI_PROVIDERS, AI_TASKS } from './ai.types.js';

export const AI_PROVIDER_TYPES = {
  OFFICIAL_SDK: 'official_sdk',
  OPENAI_COMPATIBLE: 'openai_compatible',
  CUSTOM_HTTP: 'custom_http',
};

export const AI_PROVIDER_REGISTRY = {
  [AI_PROVIDERS.GEMINI]: {
    name: AI_PROVIDERS.GEMINI,
    type: AI_PROVIDER_TYPES.OFFICIAL_SDK,
    apiKeyEnv: 'GEMINI_API_KEY',
    defaultModelEnv: 'GEMINI_DEFAULT_MODEL',
    safeDefaultModel: 'gemini-2.5-flash',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
  },
  [AI_PROVIDERS.OPENAI]: {
    name: AI_PROVIDERS.OPENAI,
    type: AI_PROVIDER_TYPES.OPENAI_COMPATIBLE,
    apiKeyEnv: 'OPENAI_API_KEY',
    defaultModelEnv: 'OPENAI_DEFAULT_MODEL',
    baseUrlEnv: 'OPENAI_BASE_URL',
    safeDefaultBaseUrl: 'https://api.openai.com/v1',
    safeDefaultModel: 'gpt-4.1-mini',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS, AI_TASKS.OUTREACH_MESSAGE, AI_TASKS.LEAD_LIST_SUMMARY],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
  },
  [AI_PROVIDERS.ANTHROPIC]: {
    name: AI_PROVIDERS.ANTHROPIC,
    type: AI_PROVIDER_TYPES.CUSTOM_HTTP,
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    defaultModelEnv: 'ANTHROPIC_DEFAULT_MODEL',
    safeDefaultBaseUrl: 'https://api.anthropic.com/v1',
    safeDefaultModel: 'claude-3-5-sonnet-latest',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS, AI_TASKS.OUTREACH_MESSAGE, AI_TASKS.LEAD_LIST_SUMMARY],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
  },
  [AI_PROVIDERS.DEEPSEEK]: {
    name: AI_PROVIDERS.DEEPSEEK,
    type: AI_PROVIDER_TYPES.OPENAI_COMPATIBLE,
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    defaultModelEnv: 'DEEPSEEK_DEFAULT_MODEL',
    baseUrlEnv: 'DEEPSEEK_BASE_URL',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
    requiresBaseUrl: true,
  },
  [AI_PROVIDERS.KIMI]: {
    name: AI_PROVIDERS.KIMI,
    type: AI_PROVIDER_TYPES.OPENAI_COMPATIBLE,
    apiKeyEnv: 'KIMI_API_KEY',
    defaultModelEnv: 'KIMI_DEFAULT_MODEL',
    baseUrlEnv: 'KIMI_BASE_URL',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
    requiresBaseUrl: true,
  },
  [AI_PROVIDERS.QWEN]: {
    name: AI_PROVIDERS.QWEN,
    type: AI_PROVIDER_TYPES.OPENAI_COMPATIBLE,
    apiKeyEnv: 'QWEN_API_KEY',
    defaultModelEnv: 'QWEN_DEFAULT_MODEL',
    baseUrlEnv: 'QWEN_BASE_URL',
    supportedTasks: [AI_TASKS.LEAD_ANALYSIS],
    supportsJson: true,
    supportsText: true,
    supportsStreaming: false,
    implemented: true,
    requiresBaseUrl: true,
  },
};

